name: Build and Push Container

on:
  push:
    branches: [main]

env:
  REGISTRY: forgejo.apps.home.tomaskral.eu
  IMAGE: ${{ github.repository }}

jobs:
  build:
    runs-on: docker
    container:
      image: quay.io/podman/stable
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Login to Forgejo Container Registry
        run: echo "${{ secrets.FORGEJO_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      - name: Build image
        run: podman build -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} .

      - name: Push image
        run: |
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
