name: Build and Push Container

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: forgejo.apps.home.tomaskral.eu
  IMAGE: ${{ github.repository }}

jobs:
  build:
    runs-on: docker
    container:
      image: docker:cli
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout
        run: git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .

      - name: Login to Forgejo Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push image
        run: >
          docker buildx build --push
          -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
          -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
          .
